services:
  mysql_db:
    image: mysql:8.0
    container_name: floreria_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: floreria_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # <-- Ruta desde la raíz
    networks:
      - floreria_network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  api_tienda:
    build: ./api_tienda
    container_name: floreria_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: mysql_db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: floreria_db
      JWT_SECRET: your-super-secret-jwt-key
    depends_on:
      - mysql_db
    networks:
      - floreria_network
    # Esperar a que MySQL esté listo
    command: sh -c "sleep 30 && node dist/app.js"

  cliente_tienda:
    build: ./cliente_tienda
    container_name: floreria_cliente
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api_tienda
    networks:
      - floreria_network

networks:
  floreria_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local