version: '3.8'

services:
  # Base de datos MySQL
  mysql_db:
    image: mysql:8.0
    container_name: floreria_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: floreria_db
      MYSQL_USER: floreria_user
      MYSQL_PASSWORD: floreria_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - floreria_network

  # Backend API
  api_tienda:
    build: ./api_tienda
    container_name: floreria_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: mysql_db
      DB_USER: floreria_user
      DB_PASSWORD: floreria_password
      DB_NAME: floreria_db
      JWT_SECRET: your-super-secret-jwt-key
      NODE_ENV: production
    depends_on:
      - mysql_db
    networks:
      - floreria_network
    volumes:
      - ./api_tienda:/app
      - /app/node_modules

  # Frontend Vue
  cliente_tienda:
    build: ./cliente_tienda
    container_name: floreria_cliente
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api_tienda
    networks:
      - floreria_network

networks:
  floreria_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local